name: Serverlist form
description: Add a eaglercraft/replit server
title: "server"
body:
- type: checkboxes
  attributes:
    label: replit server?
    description: is the eaglercraft server made in replit?
    options:
    - label: the server is made in replit
  attributes:
    label: eaglercraft server?
    description: is the eaglercraft server made in an paid host and is the eaglercraft server 24/7 on?
    options:
    - label: the server is made in an paid,24/7 host
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!
      
      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: dropdown
  id: browsers
  attributes:
    label: What browsers are you seeing the problem on?
    multiple: true
    options:
      - Firefox
      - Chrome
      - Safari
      - Microsoft Edge
